version: '3.7'

services:
  sqldb:
    image: percona
    ports:
      - 3308:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app
#    volumes:
#      - ./database/migrations:/docker-entrypoint-initdb.d/